### ISSUE TITLE
setup.py shebang does not work in new Ubuntu installs

### ISSUE THREAD

**Issue by mhaig** [mhaig/vimfiles#7]
Newer versions of Ubuntu (at least 20.04) install only `python3` by default.  This means there is no binary or script name `python` on the system by default.  It is easily resolved by installing a new package (`python-is-python3`) but it would be nice to handle this scenario and not require the additional package.

**Comment by mhaig** [comment]
Applies to `buildtool` as well.

**Comment by drmikehenry** [comment]
Thanks!  I've fixed the shebangs for `buildtool` and `setup.py` to use `python3` in <https://github.com/drmikehenry/vimfiles>.

**Comment by mhaig** [comment]
Closed via https://github.com/drmikehenry/vimfiles/commit/cb6c664083a8baca5f728dff2ad39236418e8653 and https://github.com/drmikehenry/vimfiles/commit/f4c4c92b90ee20d93c82d08a9b2296fce0c63c88
